version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    hostname: prisma
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: mysecret42
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  api:
    build: .
    hostname: api
    ports:
      - "4000:4000"
  web:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    ports: 
      - "3000:80"
volumes:
  postgres: